//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Management.Instrumentation;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class name {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value { get; set; } = "";
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class npc {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name { get; set; } = "";
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class pre {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("At", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public preAT[] At { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Has")]
    public Has[] Has { get; set; }

    [System.Xml.Serialization.XmlElementAttribute("KnowsLocation")]
    public KnowsLocation[] KnowsLocations { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("global")]
    public global[] global { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class preAT {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string location { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Has {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class KnowsLocation {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class global {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Has")]
    public Has[] Has { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("effect")]
    public effect[] effect { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class effect {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class choices {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("choice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public choicesChoice[] choice { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("repeatChoice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public choicesRepeatChoice[] repeatChoice { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("onceChoice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public choicesOnceChoice[] onceChoice { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class choicesChoice {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name { get; set; }
}

public class Choice {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public name name { get; set; } = new name();

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pre")]
    public pre Pres { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("results")]
    public results results { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class choicesRepeatChoice : Choice {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class choicesOnceChoice : Choice {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class results {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string wingame { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("effectResults", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resultsEffectResults effectResults { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("name", typeof(name), IsNullable=false)]
    public name[] locationResults { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("choices")]
    public choices choicesResults { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultsEffectResults {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("global")]
    public global[] global { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("effect")]
    public effect[] Effect { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class location {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("choices", typeof(choices))]
    public choices Choices { get; set; }

    [System.Xml.Serialization.XmlElementAttribute("pre", typeof(pre))]
    public pre Pre { get; set; }

    [System.Xml.Serialization.XmlElementAttribute("name", typeof(name))]
    public name Name { get; set; } = new name();

    [System.Xml.Serialization.XmlElementAttribute("npcs", typeof(locationNpcs),
        Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public locationNpcs[] Npcs { get; set; }

    [System.Xml.Serialization.XmlElementAttribute("quests", typeof(locationQuests), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public locationQuests Quests { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class locationNpcs {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("npc")]
    public npc Npc { get; set; } = new npc();
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class locationQuests {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("repeatableQuest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public locationQuestsRepeatableQuest[] RepeatableQuest { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("oneshotQuest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public locationQuestsOneshotQuests[] OneshotQuest { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("randomQuest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public locationQuestsRandomQuests[] RandomQuest { get; set; }
}

public class Quest {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public name Name { get; set; } = new name();
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pre")]
    public pre Pres { get; set; }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("choices")]
    public choices Choices { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class locationQuestsRepeatableQuest : Quest {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class locationQuestsOneshotQuests : Quest {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class locationQuestsRandomQuests : Quest {
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("npc", typeof(npc), IsNullable=false)]
    public npc[] Npc { get; set; }
}
