//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class name {
    private string val = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("value")]
    public string Value { get { return val; } set { val = value; } }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class npc {
    private string name = "";
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name { get { return name; } set { name = value; } }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class pre {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("At", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public preAT[] At { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Has")]
    public Has[] Has { get; set; }

    [System.Xml.Serialization.XmlElementAttribute("KnowsLocation")]
    public KnowsLocation[] KnowsLocations { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("global")]
    public global[] global { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class preAT {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string location { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Has {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class KnowsLocation {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class global {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Has")]
    public Has[] Has { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("effect")]
    public effect[] effect { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class effect {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class choices {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("choice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public choicesChoice[] choice { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("repeatChoice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public choicesRepeatChoice[] repeatChoice { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("onceChoice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public choicesOnceChoice[] onceChoice { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class choicesChoice {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name { get; set; }
}

[Serializable]
public class Choice {
    private name name = new name();
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public name Name { get { return name; } set { name = value; } }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pre")]
    public pre Pres { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("results")]
    public results results { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class choicesRepeatChoice : Choice {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class choicesOnceChoice : Choice {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class results {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string wingame { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("effectResults", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resultsEffectResults effectResults { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("name", typeof(name), IsNullable=false)]
    public name[] locationResults { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("choices")]
    public choices choicesResults { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultsEffectResults {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("global")]
    public global[] global { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("effect")]
    public effect[] Effect { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class location {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("choices", typeof(choices))]
    public choices Choices { get; set; }

    [System.Xml.Serialization.XmlElementAttribute("pre", typeof(pre))]
    public pre Pre { get; set; }

    private name name = new name();

    [System.Xml.Serialization.XmlElementAttribute("name", typeof(name))]
    public name Name { get { return name; } set { name = value; } }

    [System.Xml.Serialization.XmlElementAttribute("npcs", typeof(locationNpcs),
        Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public locationNpcs[] Npcs { get; set; }

    [System.Xml.Serialization.XmlElementAttribute("quests", typeof(locationQuests), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public locationQuests Quests { get; set; }

    public override bool Equals(object obj) {
        if (obj is location) {
            var other = obj as location;
            return other.name.Value.Equals(name.Value);
        }
        return false;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class locationNpcs {
    private npc npc = new npc();
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("npc")]
    public npc Npc { get { return npc; } set { npc = value; } }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class locationQuests {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("repeatableQuest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public locationQuestsRepeatableQuest[] RepeatableQuest { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("oneshotQuest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public locationQuestsOneshotQuests[] OneshotQuest { get; set; }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("randomQuest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public locationQuestsRandomQuests[] RandomQuest { get; set; }
}

[Serializable]
public class Quest {
    private name name = new name();
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public name Name { get { return name; } set { name = value; } }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pre")]
    public pre Pres { get; set; }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("choices")]
    public choices Choices { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class locationQuestsRepeatableQuest : Quest {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class locationQuestsOneshotQuests : Quest {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class locationQuestsRandomQuests : Quest {
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("npc", typeof(npc), IsNullable=false)]
    public npc[] Npc { get; set; }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Backgrounds {

    private BackgroundsBackground[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Background", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BackgroundsBackground[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BackgroundsBackground {

    private string nameField;

    private string descriptionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}